name: CI
on: [push, pull_request]
jobs:
  run:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.11
      with:
        variant: 'CS'
        version: '8.11.1'
    - run: raco pkg install --name review
    - run: racket run-tests.rkt
      env:
        BATCH: x
