name: CI
on: [push, pull_request]
jobs:
  run:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v0.5
    - run: raco pkg install --name review
    - run: racket run-tests.rkt
      env:
        BATCH: x
